# Generated by Django 2.2.3 on 2019-07-28 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_todolistshare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistshare',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='todolist.TodoList'),
        ),
    ]
