# Generated by Django 2.2.3 on 2019-07-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default='2019-07-29'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(default='2019-07-29'),
        ),
    ]
